apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: webapp
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: webapp